version: '3'
services: 
  container1:
    image: s222492963/node-web-app
    command: sh -c "echo 'Hello from the container viraj!' && node server.js"
    ports:
      - "3000:8080"
    expose:
      - "3000"
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 60s
      timeout: 60s
      retries: 3